import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useAccount, useNetwork } from "wagmi";
import Account from "../components/Account";
import Connect from "../components/Connect";
import styles from "../styles/Home.module.css";
import { getShortAddress } from "../utils";

const Home: NextPage = () => {
  const [{ data: accountData }] = useAccount();
  const [{ data: networkData }] = useNetwork();
  const [currentAccount, setCurrentAccount] = useState<string | undefined>("");
  const [currentChainId, setCurrentChainId] = useState<number>();

  useEffect(() => {
    setCurrentAccount(accountData?.address);
    setCurrentChainId(networkData?.chain?.id);
  }, []);

  useEffect(() => {
    const accountAddress = accountData?.address;
    if (accountAddress && accountAddress !== currentAccount) {
      setCurrentAccount(accountAddress);
      toast(
        `Account switched to ${getShortAddress(accountAddress) ?? "undefined"}`,
        { autoClose: 2000 }
      );
    }
  }, [accountData]);

  useEffect(() => {
    const chainId = networkData?.chain?.id;
    if (chainId && chainId !== currentChainId) {
      const unsupported = networkData.chain.unsupported;
      setCurrentChainId(chainId);
      toast(`Chain switched to ${networkData.chain.name}.`, {
        autoClose: 2000,
      });
    }
  }, [networkData]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Your DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ToastContainer />
        <h1 className={styles.title}>Welcome to your new DApp</h1>
        <div className={styles.connectorContainer}>
          <div className={styles.containerPadding}>
            {accountData ? <Account /> : <Connect />}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
