import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useAccount, useConnect } from "wagmi";
import styles from "../styles/Home.module.css";

const ConnectorComponent = () => {
  const [{ data, error }, connect] = useConnect();
  console.log(data);
  return (
    <div>
      {data.connectors.map((x) => (
        <button
          className={styles.connectorButton}
          key={x.id}
          onClick={() => connect(x)}
        >
          {x.name}
          {!x.ready && " (unsupported)"}
        </button>
      ))}

      {error && <div>{error?.message ?? "Failed to connect"}</div>}
    </div>
  );
};
//@ts-ignore
const AccountComponent = ({ accountData, error, loading, disconnect }) => {
  return (
    <div className={styles.container}>
      {accountData.ens?.name ? accountData.ens.name : accountData.address}
      <p>Connected to {accountData.connector.name}</p>
      <button
        className={styles.cta}
        onClick={() => {
          disconnect();
        }}
      >
        Disconnect
      </button>
    </div>
  );
};

const Home: NextPage = () => {
  const [{ data: accountData, error, loading }, disconnect] = useAccount({
    fetchEns: true,
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to your new DApp</h1>
        <div className={styles.connectorContainer}>
          <div className={styles.containerPadding}>
            {accountData ? (
              <AccountComponent
                accountData={accountData}
                error={error}
                loading={loading}
                disconnect={disconnect}
              />
            ) : (
              <ConnectorComponent />
            )}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
