import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useAccount } from "wagmi";
import Account from "../components/Account";
import Connect from "../components/Connect";
import GreeterContractInfo from "../components/GreeterContractInfo";
import Network from "../components/Network";
import PaddedContainer from "../components/PaddedContainer";
import styles from "../styles/Home.module.css";
import { getShortAddress } from "../utils";

const Home: NextPage = () => {
  const [{ data: accountData }] = useAccount();
  const [currentAccount, setCurrentAccount] = useState<string | undefined>("");

  useEffect(() => {
    setCurrentAccount(accountData?.address);
  }, []);

  useEffect(() => {
    const accountAddress = accountData?.address;
    if (accountAddress && accountAddress !== currentAccount) {
      setCurrentAccount(accountAddress);
      toast(
        `Account switched to ${getShortAddress(accountAddress) ?? "undefined"}`,
        { autoClose: 2000 }
      );
    }
  }, [accountData]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Your DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ToastContainer />
        <h1 className={styles.title}>Welcome to your new DApp</h1>
        <PaddedContainer>
          {accountData ? (
            <div>
              <Account />
              <Network />
            </div>
          ) : (
            <Connect />
          )}
        </PaddedContainer>
        {accountData && (
          <PaddedContainer>
            <GreeterContractInfo />
          </PaddedContainer>
        )}
      </main>
    </div>
  );
};

export default Home;
