import Head from "next/head";

type LayoutProps = {
  children?: JSX.Element | JSX.Element[];
};

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Your DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my-12 flex flex-col items-center">{children}</main>
    </>
  );
}
